# Generated by Django 3.2.9 on 2021-11-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remaindertasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RemainderTasks',
            new_name='RemainderTask',
        ),
    ]
