# Generated by Django 3.2.9 on 2021-11-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_remaindertasks_remaindertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remaindertask',
            name='remainder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.remainder'),
        ),
    ]
